export default {
    // 小程序登录
    'wxlogin': '/login',
    // 用户授权
    'setuserinfo': '/auth',
    // 获取用户资料
    'renting': '/renting',
    // 身份证上传地址
    'rentingupfile': '/upfile',
    // 通知列表
    'notices': '/renting/notice',
    // 咨询列表
    articles: '/articles',
    // 资讯内容统计
    articlesCount: '/articles/count',
    // 推荐房源
    recommend: '/fang/recommend',
    // 房源属性
    attr: '/fang/attr',
    // 房源列表
    fangs: '/fangs',
    // 看房记录添加
    addfangrec: '/fangs/rec',
    // 添加收藏房源
    fav: '/favs',
    // 查询是否收藏房源
    isfav: '/favs/bool',
    // 个人已租房
    myhome: '/fangs/rented',
    // 房源快搜属性
    qattr: '/attr',
    // 房源搜索
    search: '/fangs/search',
}